### ISSUE TITLE
doesn't work with babel-watch

### ISSUE THREAD

**Issue by gferreri** [detrohutt/babel-plugin-inline-import-graphql-ast#10]
I'm using [babel-watch](https://www.npmjs.com/package/babel-watch) for developing my application. I start my app with the command

```
BABEL_DISABLE_CACHE=1 babel-watch --extensions ".js, .jsx, .gql" --watch lib  lib/index.js
```

When I make a change to a `.gql` file, a restart is triggered, but the changes I made to the .gql file are not reflected when the app restarts. I have to kill the process and run the command again for `.gql` file changes to be included.

**Comment by detrohutt** [comment]
Sometimes `BABEL_DISABLE_CACHE=1` doesn't seem to actually do anything. You would probably need to manually delete the node_modules/.cache folder on each restart. I usually do that in my npm start script with something like `rm -rf node_modules/.cache && babel-node index.js`. I'm not sure how you would accomplish that using `babel-watch`. Maybe you could do something like this:
```javascript
process.on('exit', () => fs.rmdirSync('./node_modules/.cache'))
```

In any case, I don't believe there is anything I can do at the plugin level to avoid this behavior, unfortunately.
