### ISSUE TITLE
Query string does not resolve the imports

### ISSUE THREAD

**Issue by eskimoblood** [detrohutt/babel-plugin-inline-import-graphql-ast#15]
I try to use the tool to get my graphql files imported when running my tests. Unfortunately the `body` part is still the original one with the `import` statement, while I would assume it renders the imported fragments instead.

**Comment by detrohutt** [comment]
Sorry for the late response. If you're still interested in using this, I'll do my best to help if you can provide some code examples of what you are trying to do.
