### ISSUE TITLE
What is the difference between this and babel-plugin-inline-import ?

### ISSUE THREAD

**Issue by deb0ch** [detrohutt/babel-plugin-inline-import-graphql-ast#19]
After reading the README I still can't really wrap my head around what exactly this package enables for graphql files in addition to what `babel-plugin-inline-import` already does ?

**Comment by detrohutt** [comment]
That package doesn’t parse the graphql file as AST, just returns the contents as a string. Probably useful on server-side for building typedefs from graphql files containing types. My package is for converting frontend graphql files containing operations (queries/mutations/subscriptions) into an AST object to be passed to something like the graphql() function from react-apollo.

**Comment by deb0ch** [comment]
Oh, I understand better now, thank you !

So, this is especially useful on he client side then ? Should I use `babel-plugin-inline-import` on the server side or do you still recommend using `babel-plugin-inline-import-graphql-ast` on the server ?

**Comment by detrohutt** [comment]
Personally, I just use the nodejs readFileSync function to read my server-side graphql files, so I’m not familiar with any other method so can’t really make a recommendation, but my package would not be useful on the server in any scenario I’m aware of.

**Comment by detrohutt** [comment]
Perhaps surprisingly, I’ve never actually used babel-plugin-inline-import. I just needed an example of how to write a babel plugin and it seemed very similar to what i wanted to do so i forked it to start work on my package.

**Comment by deb0ch** [comment]
Apparently `babel-plugin-inline-import` is very simple, i will just put the file's contents into a variable as a string.

So, on the client side, how would having an imported graphql file parsed into a graphql ast, as in your plugin, make one's life easier than just having it in the form of a string, as in `babel-plugin-inline-import` ? Beside support for fragments, that seems by istself like a very big plus.

I'm still new to js, graphql or web development in general, hence my questions that could seem obvious to you.

**Comment by detrohutt** [comment]
My package was built to be used with Apollo-client which requires the graphql code to be in AST form. So without my package you’d need to import gql as well as use some method to get the graphql contens from the file manually and parse each operation yourself and would lose support for multiple operations in a single file.

**Comment by deb0ch** [comment]
Thank you so much for your answers, I understand much better the use and purpose of your package !
