### ISSUE TITLE
Fails to import schema files with more than one definition  

### ISSUE THREAD

**Issue by stolinski** [detrohutt/babel-plugin-inline-import-graphql-ast#21]
For instance a file containing each of the following.

This imports correctly
```
type Affiliate {
  _id: String!
  ref: String!
  name: String
  paypalEmail: String
  userId: String!
  rate: Float
}
```

This imports as undefined
```
type Affiliate {
  _id: String!
  ref: String!
  name: String
  paypalEmail: String
  userId: String!
  rate: Float
}

input AffiliateInput {
  _id: String!
  ref: String!
  name: String
  paypalEmail: String
  userId: String!
  rate: Float
}

extend type Query {
  affiliates: [Affiliate]
}

extend type Mutation {
  createAffiliate(affiliate: AffiliateInput): Affiliate
  updateAffiliate(affiliate: AffiliateInput): Affiliate
}

```

**Comment by detrohutt** [comment]
This package parses the imported file with the ‘gql’ template literal so it’s intended to be used with files containing operations, not schemas. I believe what you’re looking for is ‘babel-plugin-inline-import’ which does no parsing and just inmports the raw content.

**Comment by stolinski** [comment]
Can you use this with babel-plugin-inline-import though? I still need parsing for operations.

**Comment by detrohutt** [comment]
Hmm, good question. I’ve never tried it, but I suspect they would conflict since both replace the import statements for ‘.gql’/‘.graphql’ files. So when the second plugin ran, there’d be no graphql imports left to process. I’d be open to offering suport for a third extension (i think i’ve seen ‘.graphqls’ in use before) not supported by inline-import, so files with that extension would be left alone for my plugin to process.

**Comment by detrohutt** [comment]
Ah, actually I just took another look at the code for `babel-plugin-inline-import` and it appears it doesn't support `.gql` files, only `.graphql`, so my recommendation would be to use `.gql` files on the frontend with your operations in them, and `.graphql` files on the backend with schema info. You shouldn't run into any issues using the two packages together that way.

**Comment by detrohutt** [comment]
Oh I forgot to mention, if you do as I recommended above, you'll need to put his plugin before mine in your .babelrc. Otherwise, my plugin would process the `.graphql` files before his had the chance.

**Comment by stolinski** [comment]
I had that same thought. Another option would be to fork this and have some kind of a pass-through for non-operations where if it wasn't a query, mutation or subscription then it would just return the raw. Thanks for your ideas & help, I'll see if I can get something going.

**Comment by detrohutt** [comment]
Yeah, that's not a bad idea. I think it'd be pretty trivial to implement as well. I'll take a crack at it now and let you know what I come up with. Also, thanks for your videos on youtube. I'm a subscriber. Good stuff.

**Comment by stolinski** [comment]
That's awesome! I'd be super excited to have that as an option. Seriously appreciate the response. I'll def be featuring this plugin in some GraphQL content I have coming up. Working with .graphql files is just so much more elegant than wrapping everything in a gql.

**Comment by detrohutt** [comment]
Alright, I've got the initial implementation finished and passing a simple test. I've published it as `babel-plugin-inline-import-graphql-ast@2.3.0`. Let me know if that works for you!

**Comment by stolinski** [comment]
That's amazing. I'll try it out!

**Comment by stolinski** [comment]
Works perfectly! You are the man.

**Comment by detrohutt** [comment]
Hey @stolinski just a heads up a bug was found that affects operations with fragments. Please upgrade to v2.3.2.
