### ISSUE TITLE
Option to import fragment as AST

### ISSUE THREAD

**Issue by kamal** [detrohutt/babel-plugin-inline-import-graphql-ast#23]
The latest release broke code that expected fragment to be an AST instead of a raw string. In my app, I had something similar to

```typescript
import DeliveryFragment from '../graphql/deliveryFragment.graphql'

apolloClient.writeFragment({
  id: `Delivery:${id}`,
  fragment: DeliveryFragment,
  data: delivery,
})
```

Perhaps inline `#import` statements could continue to be raw strings, but importing as a module would yield an AST?

**Comment by detrohutt** [comment]
Ah, I hadn't considered that use case. I'll fix it right now. Give me a few minutes and I'll let you know when I've published the new version. Then your code should work again without changes once you upgrade.

**Comment by detrohutt** [comment]
Alright @kamal , should be fixed in `babel-plugin-inline-import-graphql-ast@2.3.3`! Let me know if you have any more problems. Thanks for reporting!

**Comment by kamal** [comment]
It works!
