### ISSUE TITLE
Nextjs example showing { Invariant Violation: Argument of 'query' passed to parser was not a valid GraphQL DocumentNode }

### ISSUE THREAD

**Issue by flexlee** [detrohutt/babel-plugin-inline-import-graphql-ast#26]
Hi, I was using this plugin v2.3.5 with nextjs `with-apollo` example. I have set up `.babelrc` according to instruction and took out the graphql query in `PostList.js` component to file `allPosts.graphql`. However I kept getting

```
{ Invariant Violation: Argument of   query allPosts($first: Int!, $skip: Int!) {
    allPosts(orderBy: createdAt_DESC, first: $first, skip: $skip) {
      id
      title
      votes
      url
      createdAt
    }
    _allPostsMeta {
      count
    }
  }
 passed to parser was not a valid GraphQL DocumentNode. You may need to use 'graphql-tag' or another method to convert your operation into a document
```

Could it be `babel-core` v6.26.0 that's causing this? I have uploaded the repo here https://github.com/flexlee/with-apollo-app. It would be nice to have a working example. Thank you.

**Comment by detrohutt** [comment]
It looks like you have the first line of your graphql file indented. My package doesn’t currently trim or account for leading whitespace on the first non-comment line and checks that it starts with “query”, “mutation”, “subscription”, or “fragment”. I’ll make the check a little more robust later but for now just remove the spaces at the beginning of line 1 of the allPosts.graphql file.

**Comment by flexlee** [comment]
Sorry, I fixed the indention. But it's giving me the same error.

**Comment by flexlee** [comment]
@detrohutt you're right. It works now. Thanks.
