### ISSUE TITLE
provide raw query

### ISSUE THREAD

**Issue by RevelsGit** [detrohutt/babel-plugin-inline-import-graphql-ast#3]
`graphql-tag/loader` with webpack provides raw query in `loc.source.body` and this plugin does not. It can be useful if you need to pass a query to `graphql` function.
Example:
```
import { graphql } from 'graphql';
import schema from './schema';
import myQuery from './myQuery.graphql';

graphql(schema, myQuery);
```

```
TypeError: Must provide Source. Received: [object Object]
```

I can do that with `fs.readFileSync('./myQuery.graphql', 'utf8');` but it just feels clunky.

**Comment by detrohutt** [comment]
@RevelsGit I raised an issue on graphql-tag. I'll get this added as soon as I figure out the best way to do it.

**Comment by detrohutt** [comment]
Should be good to go once you upgrade to v2.0.0!
