### ISSUE TITLE
babel 7 configuration format

### ISSUE THREAD

**Issue by elmpp** [detrohutt/babel-plugin-inline-import-graphql-ast#30]
Hi there,

I'm trying to bumble my way through to having a working babel7-based setup but there seems to be something wrong the moment i pull in "babel-plugin-inline-import-graphql-ast"

Here is my `babel.config.js` (this is now the [babel7 method](https://github.com/facebook/jest/issues/6053#issuecomment-383632515) to specify a project-wide babel config, in lieu of `.babelrc`):

```
// https://github.com/babel/babel/pull/7358#issuecomment-388311941
module.exports = {
  overrides: [{
    test: '*',
    presets: [
      ['@babel/preset-env', {'node': 'current'}],
    ],
    plugins: [
      [
        "babel-plugin-inline-import",
        {
          extensions: [
            ".css"
          ]
        }
      ],
      "babel-plugin-inline-import-graphql-ast"
    ],
    env: {
      development: {
        presets: [
          "next/babel",
        ]
      },
      production: {
        presets: [
          [
            "next/babel",
            {
              ["preset-env"]: {
                targets: {
                  browsers: "> 5%"
                }
              }
            }
          ]
        ]
      },
      test: {
        presets: [
          [
            "next/babel",
            {
              ["preset-env"]: {
                modules: true
              }
            }
          ]
        ]
      }
    }
  }],
  ignore: [
    "/*.plain/"
  ]
}
```

Example usage of the graphql inlining:

```
# ---- https://github.com/apollographql/graphql-tag
#import "./Category3Fragment.graphql"
#import "./Category2Fragment.graphql"
#import "./Category1Fragment.graphql"


query Category1(
  $canonicalised_name: String,
  $category1__canonicalised_name: String,
) {
  category1 (
    canonicalised_name: $canonicalised_name,
    category1__canonicalised_name: $category1__canonicalised_name,
  ) {
      ...Category1Fragment
  }
}
```

Error text:

```
Module build failed: Error: Configuration contains explicit test/include/exclude checks, but no filename was passed to Babel
    at configFieldIsApplicable (/Users/matt/dev/partridge/frontend/node_modules/@babel/core/lib/config/config-chain.js:401:11)
    at configIsApplicable (/Users/matt/dev/partridge/frontend/node_modules/@babel/core/lib/config/config-chain.js:396:41)
    at forEach (/Users/matt/dev/partridge/frontend/node_modules/@babel/core/lib/config/config-chain.js:242:13)
    at Array.forEach (<anonymous>)
    at /Users/matt/dev/partridge/frontend/node_modules/@babel/core/lib/config/config-chain.js:239:42
    at buildRootChain (/Users/matt/dev/partridge/frontend/node_modules/@babel/core/lib/config/config-chain.js:90:20)
    at loadPrivatePartialConfig (/Users/matt/dev/partridge/frontend/node_modules/@babel/core/lib/config/partial.js:51:55)
    at loadFullConfig (/Users/matt/dev/partridge/frontend/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/matt/dev/partridge/frontend/node_modules/@babel/core/lib/transform-sync.js:15:38)
    at buildVariableAST (/Users/matt/dev/partridge/frontend/node_modules/babel-plugin-inline-import-graphql-ast/build/index.js:87:58)
    at /Users/matt/dev/partridge/frontend/node_modules/babel-plugin-inline-import-graphql-ast/build/index.js:72:26
    at Array.map (<anonymous>)
    at buildReplacements (/Users/matt/dev/partridge/frontend/node_modules/babel-plugin-inline-import-graphql-ast/build/index.js:65:31)
    at PluginPass.exit (/Users/matt/dev/partridge/frontend/node_modules/babel-plugin-inline-import-graphql-ast/build/index.js:59:34)
    at newFn (/Users/matt/dev/partridge/frontend/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:237:21)
    at NodePath._call (/Users/matt/dev/partridge/frontend/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:20)
```

**Comment by detrohutt** [comment]
Would you mind running `npm list @babel/core` and letting me know what version that outputs? (It could be different from what's in your `package.json`). Babel just released an update in the last day or two and I've not gotten around to seeing if there are any breaking changes that affect my plugin.

**Comment by detrohutt** [comment]
Wow, thanks for taking the time to detail what needs to be done @loganfsmyth! Do you think this is likely to be a breaking change (major version bump) for my plugin? I mean do you think anyone would have been relying on their config being loaded by my plugin in some way?

**Comment by elmpp** [comment]
here are both npm's and yarn's outputs for `@babel/core` (there's something funky going on with npm's resolution):

```
Matthews-MacBook-Pro:frontend matt$ npm list @babel/core
frontend@0.1.0 /Users/matt/dev/partridge/frontend
└─┬ UNMET DEPENDENCY next@6.0.2
  └── UNMET DEPENDENCY @babel/core@7.0.0-beta.42

npm ERR! missing: next@6.0.2, required by frontend@0.1.0
npm ERR! missing: @babel/core@7.0.0-beta.42, required by next@6.0.2
Matthews-MacBook-Pro:frontend matt$ yarn list !$
yarn list @babel/core
yarn list v1.6.0
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ @babel/core@7.0.0-beta.47
✨  Done in 0.64s.
```

**Comment by detrohutt** [comment]
@elmpp Thanks! It looks like you're using the newest one. I just checked the changelog and it doesn't look like it should have affected my plugin directly. Hopefully what Logan suggested will fix it for you. I'm working on making that change now and I'll ping you here when I've published the new version.

@loganfsmyth I didn't see anything in the babel-handbook about pulling `template` from the params.. is that new with Babel 7? Would *that* be a breaking change for people using my plugin with Babel 6? Should I use the `babel-template` package mentioned in the handbook instead? :confused:

**Comment by loganfsmyth** [comment]
> I didn't see anything in the babel-handbook about pulling template from the params.. is that new with Babel 7?

Nope! That's been there for ages. The first argument includes everything you get from importing babel-core itself, along with some extra stuff. That said, if you want to avoid it to keep things minimal you could also do

```
function buildVariableAST(graphqlAST, importName) {
  return t.variableDeclaration("var", [
    t.variableDeclarator(t.identifier(importName), t.valueToNode(graphqlAST)),
  ]);
}
```

**Comment by detrohutt** [comment]
@loganfsmyth Amazing. I wish I'd have known about `t.valueToNode` when I was creating this plugin. It'd have saved me many hours of frustration. Thank you for all your help!

**Comment by elmpp** [comment]
it works! Thank you very much (also to @loganfsmyth)

**Comment by detrohutt** [comment]
@elmpp Awesome! Thanks for reporting back. :)

**Comment by loganfsmyth** [comment]
@detrohutt The best you can do on the side of the transform itself would be
```
const node = t.valueToNode(graphqlAST);
node._compact = true;
```
which will force-enable the `concise` option and restrict the output to a single line with only single-space spacing. Not quite as small as the `minified` but should still be a good way there.

**Comment by detrohutt** [comment]
@loganfsmyth Amazing! Thanks for being so available for my questions. It's great to have such a wellspring of knowledge on call when I get stuck or just feel like I'm probably doing something sub-par. And thanks for all your great work on Babel!

**Comment by detrohutt** [comment]
@loganfsmyth That worked beautifully. Mind if I credit you in the CHANGELOG/Release notes/Twitter announcement?
