### ISSUE TITLE
TransformError with React Native

### ISSUE THREAD

**Issue by FredyC** [detrohutt/babel-plugin-inline-import-graphql-ast#7]
I am using the plugin for my React Native project. So far everything is working just fine, but today I run into one of the most peculiar issues ever. I have a `mutations` folder with every mutation in separate `.graphql` file. Then there is `index.js` file with the following content.

```js
export AuthenticateMutation from './Authenticate.graphql'
export SelectGameMutation from './SelectGame.graphql'
export SubmitApplicationMutation from './SubmitApplication.graphql'
export CancelApplicationMutation from './CancelApplication.graphql'
```

This fails with `TransformError: Cannot read property 'type' of undefined` 😕 

Now the funny part ... if I rename the last one to `CancelApplicationMutatio` _(the last letter removed)_, suddenly it works! It ends with same error for a name like `CancelApplicationMutatiox` or `XancelApplicationMutation` too. However `CancelApplicationMutatioxx` works just fine! Trying to move that single line around does not help anything. A content of that graphql file does not matter either, tried putting there a query from one of other files.

In a desperate moment, I tried to do this which suddenly worked just fine and then I've reverted it back to the original form ... whoa, it works too!
```js
import CancelApplicationMutation from './CancelApplication.graphql'
export { CancelApplicationMutation }
```

This feels like some weird caching issue. I know I had parser error in that query before then I fixed it. But still, why it wouldn't be working while keeping the same length of variable no matter the form?

**Comment by real34** [comment]
Hi @FredyC, it seems to be the same than #2 ... a very weird issue indeed with unbelievable workarounds :/

**Comment by detrohutt** [comment]
@FredyC @real34 I just pushed a new release candidate - 2.0.1-rc.1 - a few minutes ago. Try using that and let me know if it works for you.
`yarn add babel-plugin-inline-import-graphql-ast@beta`

**Comment by FredyC** [comment]
@detrohutt So I tried latest beta, but unfortunately no luck. The worst part is the error message like this. It's impossible to find culprit. This has happened to me after cleaning all RN cache, restarted everything. Feels like there is parse error in one of graphql files, yet when I try to manually parse all of them with `graphql-tag` it works just fine. In this case the workarounds I mentioned earlier does not work either.

![screenshot-1504038473423](https://user-images.githubusercontent.com/1096340/29842614-af3dfd90-8d09-11e7-9f0c-9da97e6b897e.jpg)
