### ISSUE TITLE
Dependency on graphql is preventing use of newer version

### ISSUE THREAD

**Issue by dlredden** [detrohutt/babel-plugin-inline-import-graphql-ast#8]
I'm digging this plugin, but it's pinned to GraphQL `^0.9.6` and when I update my project to something newer than that (i.e. 0.11.x) the project throws this lovely error "Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory."

I pulled the code and attempted to run the tests so I could upgrade the dependencies and validate that I didn't break anything, but the tests aren't working (at least not for me). Removing the dependency on GraphQL would be ideal, upgrading it would be the next best thing.

**Comment by detrohutt** [comment]
Sorry the tests were just left over from the project i forked and i never updated them. How about if I changed it to a peerDependency of >=0.9.6 ?

**Comment by dlredden** [comment]
That should do the trick

**Comment by detrohutt** [comment]
Done. Published version `2.0.2`.
